### ISSUE TITLE
LAbjack kipling to run on raspberry pi under raspbian

### ISSUE THREAD

**Issue by rogerone04** [rogerone04/D3SCANO#1]
Got the following when initializing npm library. trying to install kipling on a raspberry pi 3 running raspbian Linux:

pi@raspberrypi:~/ljswitchboard-project_manager $ npm run initialize

> ljswitchboard-project_manager@0.1.0 initialize /home/pi/ljswitchboard-project_manager
> node scripts/initialize.js

npm install
git submodule init
git submodule update
npm run checkout_master
/home/pi/ljswitchboard-project_manager/node_modules/yargs/lib/command.js:22
    globalMiddleware.push(...middlewares)
                          ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/pi/ljswitchboard-project_manager/node_modules/yargs/lib/argsert.js:2:17)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

npm ERR! Linux 4.14.34-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "checkout_master"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! ljswitchboard-project_manager@0.1.0 checkout_master: `node main.js do --dir_out -c "git checkout master"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ljswitchboard-project_manager@0.1.0 checkout_master script 'node main.js do --dir_out -c "git checkout master"'.
npm ERR! This is most likely a problem with the ljswitchboard-project_manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node main.js do --dir_out -c "git checkout master"
npm ERR! You can get their info via:
npm ERR!     npm owner ls ljswitchboard-project_manager
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/ljswitchboard-project_manager/npm-debug.log
child_process.js:484
    throw err;
    ^

Error: Command failed: npm run checkout_master
/home/pi/ljswitchboard-project_manager/node_modules/yargs/lib/command.js:22
    globalMiddleware.push(...middlewares)
                          ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/pi/ljswitchboard-project_manager/node_modules/yargs/lib/argsert.js:2:17)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

npm ERR! Linux 4.14.34-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "checkout_master"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! ljswitchboard-project_manager@0.1.0 checkout_master: `node main.js do --dir_out -c "git checkout master"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ljswitchboard-project_manager@0.1.0 checkout_master script 'node main.js do --dir_out -c "git checkout master"'.
npm ERR! This is most likely a problem with the ljswitchboard-project_manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node main.js do --dir_out -c "git checkout master"
npm ERR! You can get their info via:
npm ERR!     npm owner ls ljswitchboard-project_manager
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/ljswitchboard-project_manager/npm-debug.log

    at checkExecSyncError (child_process.js:441:13)
    at Object.execSync (child_process.js:481:13)
    at exec (/home/pi/ljswitchboard-project_manager/scripts/initialize.js:5:32)
    at Object.<anonymous> (/home/pi/ljswitchboard-project_manager/scripts/initialize.js:15:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)

npm ERR! Linux 4.14.34-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "initialize"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! ljswitchboard-project_manager@0.1.0 initialize: `node scripts/initialize.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ljswitchboard-project_manager@0.1.0 initialize script 'node scripts/initialize.js'.
npm ERR! This is most likely a problem with the ljswitchboard-project_manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/initialize.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls ljswitchboard-project_manager
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/ljswitchboard-project_manager/npm-debug.log

**Comment by rogerone04** [comment]
is this a too basic failure?
